@echo off
title Matrix Tracking Program
color 0a
mode 1000

:Greeting
cls
echo Hello Tanner
echo The MATRIX has you!
echo Click the X for the Blue pill to EXIT, 
echo Click enter for the Red Pill, just to see how deep the Rabbit hole goes!

echo ....................................................................................................
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmNNNNNmdmmmNNNNNNNNhNNNdymNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmymmNmmmmmmNdmNNNNNNmNNNhsymNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNddhNNNNNNNNNNNNNNNNNmmNNNNNmhdNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNhdddmNNNNmmmdhyo+oyhy/-:odmNmddNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNmmNNNNmdyo:.``           `-smNNmNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNmmNNmo-.`                  -smNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNmy:`                     `omNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNms:.` ``````              .dNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNmh+:.````````             .dNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNmmh+-`                     :dNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMhyNNNNdhyo++++/:-.``.`````     `./mNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNoymNNmshhdmNNNNmmmhhy/-:oyysyhddddmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMh/ddmmo-ymNNNNNNNNNNmd:`/mmmNNNNmmmmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM/yddyd:-:sdmmmNNNNmmmo` .dmmNNNNmmdmdMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM/ohyoy+:/::/oshhhysos:   /hdmmmmhyoysMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd+/shs+shyyyyso++//++:   `-:////-..-:NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdhhs/shdddhs+/::/:``    ```.-://:.-NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMhs+sdddddyo:::sooso://-.``./oy++yMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNy+ydddddyo/--smmmdhhh:.-.-/yNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMhshddmddhys++ohdhhso/``--:oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdhdddddhhddhhhdhhyyo/+/:+mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmddddddddmmmmdhhhhhhhho+yMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmddddddddddhddhhysys+osyhMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMdmdddmmmdddyysssoo+/+shy/NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMhdmmmmmmmmdhso/::--:+ys/:mNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNddmmmmmmmmmmdhhyyyyhho/--mmNmdmmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNMmhNNNmNNmmmmNNNmmmmho+:..dNNmdddhmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNMMMmhNNNNNNNNNNNNNNmmhso/-..-hNNmmdddddmNMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMNNNMMMMMMhhNNNNNNNNNNNNNmdhys+:-.``.yNNmddddyosmMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMNMMMNNMMMMMMMMm:mNNNNNNNNNNNNmdhyso+:.```.dmmmmddhs+//dMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMNNNNNNMMMMMMMMMNd-.mNNNNNNNNNNNmmdhyo+-.```-hmmdddhyyso+:/yNMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMNmmNNNNNMMMMMMMMMNNy`/NNMMNNNNNNNNmhyso+:--/oydmmmdydhyyssso+oyydNNMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMNNNNNNNMMMMMMMMMNNNNNNdmNNNMNNMNNNNmddhdhddmmNmmmddddshyooo+o+o+oso+//+shdmNNMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMNNNmNNNNNNNNNNNNNNNNNNNNNNNNNNNmmddddddoh+s+-.:++++ss/:--....-/+ydNNMMMMM
echo MMMMMMMMMMMMMMMMNMMMMMMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmdmddddddyh/+oo:.-:o/hhso+//+/::////+ydmNMM
echo MMMMMmNNMMMMMMMMMMMMMMNNNNNNNNNmmmNNNNNNNNNNNNNNNNNNNNNNdddmmmmdhhss:+.....-/:mdyoo++osssyyyyhddmNNN
echo MMNNddNNNMMMMMMNNMMMNNNNNNNNNNNmmmmmmNmNmNNNNNNNNNNNNNNdddddmdmmmNNy-/....`.-/mdyyoooosyydddddmNNNNm
echo MmmhdNNdMMMMNNNNMMMNNNNNmmmmmNmmmmmmmmmmmmNNNNNNNNNNNNddmmmNMMMMMMMms/:..-..`+dhyysoso+shhdmmmNMNNNN
echo NNmmNNNNMNNNNMMNNNNmNNmmmmmmmmmmmmmmmmmmmmNNNNNNNNNNNdmNMMMMMMMMMMMMMMdo:.:-`hdhhhyyyo/ohdmmmNMMNNNN
echo mmmNmmNNNMNNNNNNNmNNNmmmmdddmmmmmmmmmmmmmNNNNNNNNNNNmNMMMMMMMMMMMMMMMMMMNh+--mddhhhhys+:ydddmNMMMNNN
echo mmNNdmNNNNNNNNNNNNNNmmmmdmmdddmmdmmmmmmNNNNmNNNNNNNNMMMMMMMMMMMMMMNNNNNNMMMmdmmdhhhhys+:oydmNMMMMNNN
echo mNMNhNNNNNNNNNNNNMNmmdmmmmdddddmdmmmmNmNNNNNNNNNNMNMMMMMMMMMMMMMMNNNNNNNNNNNNNmNNNmdmNNNmhymNNNMMNNN
echo NNMNdNNNNNNNNNNNMNmmdddmdddddddmddmdmmmNNNNmNNNNMNMMMMMMMMMMMMMMMMMNNNNNNNNNNNNNNNmmdMMMNNNNNNMMMMNM
echo NNNdmmmmNNNNNNNNNmdddddddhhhddddddmdmmmmmmmNNNNNNMMMMMMMMMMMMMMMMMMMNNNNNNNNNNNNNNmmhNMMMMMNNNMMMMMM
echo NNNhdmNNNNNNNNNNmdddddhhhhhddddddddmmmmmmNNNNNNNMMMMMMMMMMMMMMMMMMMMNNNNNMNNNNNNNmmmhdMMMMMNNNMMMMMM
echo NNdmNNNNNNNNNNMmddddddddhdhhdhddmdmmmmmmNNNNNNNNMMMMMMMMMMMMMMMMMMMMMNNMMMMNNNNNNNmmhyMMMMMNmmNMMMMM
echo NNdmdmNNNNNMMMNmmdmmmmmmdddddddmdmmmNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMNMMMMMNNNNNmmmdyNMMMMNmhhmNMMM
echo ....................................................................................................

pause
cls
goto Matrix
:Matrix
echo %random% Deleting C: %random%%random%%random% Deleting D: %random%%random%%random% Deleting H:%random%%random%%random% Deleting I: %random%%random%%random% Deleting J: %random%%random%%random% Deleting Regestry Keys...%random%%random%%random% Deleting Regestry Keys...%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random
Ping 1.1.1.1 -n 1 -w 0.3 >NUL
goto Matrix

